### ISSUE TITLE
Error: Cannot find module './lib/agenda' in Agenda v4.0.0

### ISSUE THREAD

**Issue by marius4896** [agenda/agenda#1191]
Hello,
After updating to 4.0.0 i get an error even when importing the lib 
```
node src/app.js 
\internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './lib/agenda'
Require stack:
```
Node Version : 12.13.0
NPM Version: 6.14.7

Code ran:

```
require("dotenv").config();
const Agenda = require("agenda");
const agenda = new Agenda({ db: { address: process.env.MONGODB } });
```

Hope this helps
Cheers

**Comment by simison** [comment]
Yep, we'll need new release to fix it. Apologies!

It's about us being on Typescript and needing to use dist instead of sources directly.

**Comment by simison** [comment]
Fix in progress at https://github.com/agenda/agenda/pull/1193

**Comment by simison** [comment]
Hi @marius4896; 4.0.1 fixes the issue! Thanks for patience again. :-)
